[phases.build]
cmds = [
    "cd Backend && dotnet restore Azul.sln",
    "cd Backend && dotnet publish Azul.Api/Azul.Api.csproj -c Release -o out --no-restore"
]

[phases.start]
cmd = "dotnet Backend/out/Azul.Api.dll"

[variables]
DOTNET_ROOT = "/nix/store/*-dotnet-sdk-*/share/dotnet" 